<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXaWHrKA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXaWHrKA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXaWHrKA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXaWHrKA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXaWHrKA\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XaWHrKA',
    'container.build_id' => '7a126456',
    'container.build_time' => 1523034177,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXaWHrKA');
